<%= form_with(model: @user, local: true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "") %> 件のエラーが発生しました:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :email, id: :user_email, placeholder: "メールアドレス" %>
  </div>

  <div class="field">
    <%= f.text_field :name, id: :user_name, placeholder: "ユーザーネーム" %>
  </div>

  <div class="field">
    <%= f.password_field :password, name: "user[password]", placeholder: "パスワード" %>
  </div>

  <div class="field">
    <%= f.password_field :password, name: "user[password_confirmation]", placeholder: "パスワード(確認用)" %>
  </div>

  <div class="field">
    <%= f.file_field :user_image, id: :user_image %>
    <%= image_tag(@user.user_image.url) if @user.user_image && @user.user_image.url%>
    <%= f.hidden_field :image_cache %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
